### ISSUE TITLE
Why we are using the old version of wp-graphql-woocommerce?

### ISSUE THREAD

**Issue by williamtran29** [w3bdesign/nuxtjs-woocommerce#1026]
I don't know why we're still using version 0.6.2 (3 years ago).

Can we make it works with the latest version?

**Comment by w3bdesign** [comment]
> I don't know why we still use version 0.6.2 (3 years ago).
> 
> Can we make it works with the latest version?

I tried upgrading to a newer version, but it wouldn't work.

I didn't want to waste too much time on it, so I have kept it at the last known working version for now.

If you want to work on this, let me know.

I may test out a newer version, but it has not been a priority yet.

@williamtran29

**Comment by w3bdesign** [comment]
@williamtran29 

I got it to work in https://github.com/w3bdesign/nuxtjs-woocommerce/pull/1028 but I need to test my other Wordpress projects with it before I merge the pullrequest.

**Comment by w3bdesign** [comment]
@williamtran29 

This has been resolved in https://github.com/w3bdesign/nuxtjs-woocommerce/releases/tag/1.0.4
