### ISSUE TITLE
GET_SINGLE_PRODUCT_QUERY.gql

### ISSUE THREAD

**Issue by colingell** [w3bdesign/nuxtjs-woocommerce#1203]
When running the query in GET_SINGLE_PRODUCT_QUERY.gql in the GraphQL IDE (In the WPGraphQL/Woocommerce plugin) the queries can't be run on allPaColors & allPaSizes.  I've removed these from my query in my version and the product pages render without these.

**Comment by w3bdesign** [comment]
@colingell 

What error do you get?

**Comment by colingell** [comment]
In the console none, it just shows blank  in the GraphQL IDE

`{
  "errors": [
    {
      "message": "Cannot query field \"allPaColors\" on type \"VariableProduct\".",
      "extensions": {
        "category": "graphql"
      },
      "locations": [
        {
          "line": 28,
          "column": 7
        }
      ]
    },
    {
      "message": "Cannot query field \"allPaSizes\" on type \"VariableProduct\".",
      "extensions": {
        "category": "graphql"
      },
      "locations": [
        {
          "line": 33,
          "column": 7
        }
      ]
    },
    {
      "message": "Variable \"$id\" is never used in operation \"Product\".",
      "extensions": {
        "category": "graphql"
      },
      "locations": [
        {
          "line": 1,
          "column": 15
        }
      ]
    }
  ],
  "extensions": {
    "debug": [],
    "queryAnalyzer": {
      "keys": "baa95b66a2dc0ed4ada7f28514e34aced5b5cb67a608afe5c87dcb5192809cbd graphql:Query operation:Product",
      "keysLength": 96,
      "keysCount": 3,
      "skippedKeys": "",
      "skippedKeysSize": 0,
      "skippedKeysCount": 0,
      "skippedTypes": []
    }
  }
}`

**Comment by colingell** [comment]
Without this section
` allPaColors {
        nodes {
          name
        }
      }
      allPaSizes {
        nodes {
          name
        }
      }`
it runs fine

**Comment by w3bdesign** [comment]
@colingell 

What attributes do you have in your Wordpress installation?

Currently the project requires those two attributes to work properly.

**Comment by colingell** [comment]
Just one attribute setup in each product with the Name 'Size'
I take it is jus case of changing those attributes in the .gql file?

**Comment by colingell** [comment]
I'll close this Issue, it's more so that you are aware of it
