### ISSUE TITLE
localStorage is not defined

### ISSUE THREAD

**Issue by sergeypoprovka** [w3bdesign/nuxtjs-woocommerce#174]
Hi! After running `yarn start` and visiting the browser process is going down with the error:
```
ReferenceError: localStorage is not defined
```

Can you help me to pass it? Tnx.

**Comment by w3bdesign** [comment]
Hi @sergeypoprovka ,

I am doing a fresh clone of the repo and looking into it. 

What I know based on the error message you mentioned is that it is attempting to save data to the localStorage in an environment that doesn't support it (serverside).

I will get back to you as soon as I have looked into the issue.

**Comment by w3bdesign** [comment]
I believe I have

**Comment by w3bdesign** [comment]
As I have received no reply and have not received enough information to recreate the issue, I am closing this.
