### ISSUE TITLE
Editing/adding to apollo queries

### ISSUE THREAD

**Issue by Afupe** [w3bdesign/nuxtjs-woocommerce#229]
Hi!

I'm trying to edit the "single product view" so that it shows product's regular price and sale price. The code seems to be already implemented in ShowSingleProduct.vue file:

```
            <div v-if="product.onSale" class="flex">
              <p class="pt-1 pl-8 mt-4 text-2xl text-gray-900 line-through">
                {{ product.regularPrice }}
              </p>
              <p class="pt-1 mt-4 text-3xl text-gray-900">
                {{ product.salePrice }}
              </p>
            </div>

            <p v-else class="pt-1 mt-4 text-2xl text-gray-900">
              {{ product.price }}
            </p>
```

So I added "regularPrice" and "salePrice" to the "GET_SINGLE_PRODUCT_QUERY.gql" query:

```
    ... on SimpleProduct {
      price
      regularPrice     <-- 
      salePrice          <-- So I added these two lines...
      databaseId
    }
```

However, this isn't working, it just shows the "price" for the product in single product page. As I'm new to working with Apollo and GraphQL, I believe I have missed something. Do I need to make some modifications to the graphql.schema.json file aswell? I have been searching for good ways to learn mora about how GraphQL and Apollo works together with nuxt frontend / wordpress backend but the schema file is somehow intimidating (because there's already almost 100 000 lines of code lol) even though it looks somewhat simple in its format.

I'm probably trying to do similar change to the "get products by category" -view as currently it also just shows the price, not sale price and regular price together.

Sorry for bothering with this kind of trivial matter, but I would really appreciate some sort of clue of what I need to change in order to get this implemented correctly. Then I'd feel more confident in trying to implement more advanced changes in the future :)

**Comment by Afupe** [comment]
After reading more about wordpress and GraphQL integration with Apollo I figured out that I need to run that "codegen.yml", which generated a "src/generated/graphql.ts" file and updated the schema in "graphql.schema.json". Do I need to import that graphql.ts into apollo-client-config.js? Currently there's only 

`import introspectionQueryResultData from '@/graphql.schema.json'`

... and no mention about that newly generated graphql.ts file. This github project doesn't even have a "src" folder, so I'm somewhat stuck with this problem. Going to keep searching for solution for my problem tho :)

**Comment by w3bdesign** [comment]
@Afupe 

I solved the issue you mentioned in https://github.com/w3bdesign/nuxtjs-woocommerce/pull/230

You can take a look at GET_SINGLE_PRODUCT_QUERY.gql to see how I solved it, but basically I just had to add onSale as well as salePrice and regularPrice.

You don't need to import the GraphQL schema to solve this, just take a look at the pull request I opened and  linked to.

**Comment by Afupe** [comment]
Oh yeah that worked, It seems quite unintuitive right now but I'm happy that this gives me confidence to make more advanced queries and trust them to work in the future :D

**Comment by w3bdesign** [comment]
Haha, no worries
As I write this I am currently unemployed, so I have plenty of spare time.
Also, assisting others with things that I know is positive for my motivation as well as my self-esteem and mental health.

If you are interested in learning I would recommend that you check out my other Ecommerce projects:

https://github.com/w3bdesign/nextjs-woocommerce

https://github.com/w3bdesign/laravel-vue (still in development, though)

If I were you I would begin with simpler projects first before working with Ecommerce, like a TODO application.

I recommend that you take a look at https://github.com/w3bdesign/todo-hooks
