### ISSUE TITLE
Make Algolia search results look good on mobile

### ISSUE THREAD

**Issue by w3bdesign** [w3bdesign/nuxtjs-woocommerce#259]
![image](https://user-images.githubusercontent.com/45217974/109731863-5a100700-7bbc-11eb-9b8a-f1dada2ffd8f.png)

**Comment by viniciusdeliz** [comment]
I'd be happy to accomplish this :)

**Comment by w3bdesign** [comment]
> 
> 
> I'd be happy to accomplish this :)

Feel free to fork the project and open a Pull Request.

I haven't really had the time to look into this anymore as I h ave recently started a new job.

**Comment by w3bdesign** [comment]
> 
> 
> I'd be happy to accomplish this :)

@ viniciusdeliz 

Feel free to fork the project and open a Pull Request.

I haven't really had the time to look into this anymore as I h ave recently started a new job.

**Comment by w3bdesign** [comment]
> 
> 
> I'd be happy to accomplish this :)

@viniciusdeliz 

Any update on this issue yet?

**Comment by viniciusdeliz** [comment]
> > I'd be happy to accomplish this :)
> 
> @viniciusdeliz
> 
> Any update on this issue yet?

Just managed to clone and set it up by now. However I'm not able to display the thumbnails of my products. 
I can't replicate the behavior of https://nuxt.dfweb.no/search

This is how the search product results are being shown in my environment:
![image](https://user-images.githubusercontent.com/5748616/124340337-da567100-db8a-11eb-8933-fde967193160.png)

**Comment by w3bdesign** [comment]
> 
> 
> > > I'd be happy to accomplish this :)
> > 
> > 
> > @viniciusdeliz
> > Any update on this issue yet?
> 
> Just managed to clone and set it up by now. However I'm not able to display the thumbnails of my products.
> I can't replicate the behavior of https://nuxt.dfweb.no/search
> 
> This is how the search product results are being shown in my environment:
> ![image](https://user-images.githubusercontent.com/5748616/124340337-da567100-db8a-11eb-8933-fde967193160.png)

Do you have a live url I can see the issue at?

Most likely your products are setup wrong or there is something wrong with your environment variables.

**Comment by viniciusdeliz** [comment]
I don't have a Live URL.
My PLACEHOLDER_SMALL_IMAGE_URL is empty, maybe that? This info comes from Algolia?

**Comment by w3bdesign** [comment]
> 
> 
> I don't have a Live URL.
> My PLACEHOLDER_SMALL_IMAGE_URL is empty, maybe that? This info comes from Algolia?

Try adding product images to the product(s) as well as the product variations.  
I believe you must have the variations Size and Color added to the Woo setup if I remember correctly. (See the README in the project for more details).

The PLACEHOLDER_SMALL_IMAGE_URL env variable is just meant as a fallback in case the product has no image.

**Comment by w3bdesign** [comment]
@viniciusdeliz 

https://github.com/w3bdesign/nuxtjs-woocommerce/pull/385

Will close this issue.
